name: lego
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - conda-forge::tqdm
  - conda-forge::signalrcore
  - conda-forge::pillow
  - conda-forge::pandas
  - conda-forge::seaborn
  - conda-forge::psutil
  - conda-forge::ipython
  - conda-forge::pyyaml
  - conda-forge::scipy
  - conda-forge::matplotlib
  - conda-forge::numpy
  - pytorch::pytorch=1.12.0
  - pytorch::torchaudio=0.12.0
  - pytorch::torchvision=0.13.0
  - pip
  - pip:
    - opencv-python
    - uuid6 
    - tensorflow-cpu==2.8.2
    - timm
    - fiftyone==0.18.0
    - fastapi==0.86.0
    - loguru
    - uvicorn[standard]
    - SQLAlchemy
    - gitpython